/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DemoExample {
        /**
          * The middle name
         */
        "content": string;
        "openModal": () => Promise<void>;
        /**
          * The first name
         */
        "title": string;
    }
    interface HomeButtons {
        "buttonTitle": string;
    }
    interface HomeCards {
        /**
          * The middle name
         */
        "content": string;
        "openModal": () => Promise<void>;
        /**
          * The first name
         */
        "title": string;
    }
    interface HomeFooter {
        "homeTitle": string;
    }
    interface HomeHeader {
        "haederTitle": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PageHome {
    }
    interface PageTome {
    }
}
declare global {
    interface HTMLDemoExampleElement extends Components.DemoExample, HTMLStencilElement {
    }
    var HTMLDemoExampleElement: {
        prototype: HTMLDemoExampleElement;
        new (): HTMLDemoExampleElement;
    };
    interface HTMLHomeButtonsElement extends Components.HomeButtons, HTMLStencilElement {
    }
    var HTMLHomeButtonsElement: {
        prototype: HTMLHomeButtonsElement;
        new (): HTMLHomeButtonsElement;
    };
    interface HTMLHomeCardsElement extends Components.HomeCards, HTMLStencilElement {
    }
    var HTMLHomeCardsElement: {
        prototype: HTMLHomeCardsElement;
        new (): HTMLHomeCardsElement;
    };
    interface HTMLHomeFooterElement extends Components.HomeFooter, HTMLStencilElement {
    }
    var HTMLHomeFooterElement: {
        prototype: HTMLHomeFooterElement;
        new (): HTMLHomeFooterElement;
    };
    interface HTMLHomeHeaderElement extends Components.HomeHeader, HTMLStencilElement {
    }
    var HTMLHomeHeaderElement: {
        prototype: HTMLHomeHeaderElement;
        new (): HTMLHomeHeaderElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLPageTomeElement extends Components.PageTome, HTMLStencilElement {
    }
    var HTMLPageTomeElement: {
        prototype: HTMLPageTomeElement;
        new (): HTMLPageTomeElement;
    };
    interface HTMLElementTagNameMap {
        "demo-example": HTMLDemoExampleElement;
        "home-buttons": HTMLHomeButtonsElement;
        "home-cards": HTMLHomeCardsElement;
        "home-footer": HTMLHomeFooterElement;
        "home-header": HTMLHomeHeaderElement;
        "my-component": HTMLMyComponentElement;
        "page-home": HTMLPageHomeElement;
        "page-tome": HTMLPageTomeElement;
    }
}
declare namespace LocalJSX {
    interface DemoExample {
        /**
          * The middle name
         */
        "content"?: string;
        /**
          * The first name
         */
        "title"?: string;
    }
    interface HomeButtons {
        "buttonTitle"?: string;
    }
    interface HomeCards {
        /**
          * The middle name
         */
        "content"?: string;
        /**
          * The first name
         */
        "title"?: string;
    }
    interface HomeFooter {
        "homeTitle"?: string;
    }
    interface HomeHeader {
        "haederTitle"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PageHome {
    }
    interface PageTome {
    }
    interface IntrinsicElements {
        "demo-example": DemoExample;
        "home-buttons": HomeButtons;
        "home-cards": HomeCards;
        "home-footer": HomeFooter;
        "home-header": HomeHeader;
        "my-component": MyComponent;
        "page-home": PageHome;
        "page-tome": PageTome;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "demo-example": LocalJSX.DemoExample & JSXBase.HTMLAttributes<HTMLDemoExampleElement>;
            "home-buttons": LocalJSX.HomeButtons & JSXBase.HTMLAttributes<HTMLHomeButtonsElement>;
            "home-cards": LocalJSX.HomeCards & JSXBase.HTMLAttributes<HTMLHomeCardsElement>;
            "home-footer": LocalJSX.HomeFooter & JSXBase.HTMLAttributes<HTMLHomeFooterElement>;
            "home-header": LocalJSX.HomeHeader & JSXBase.HTMLAttributes<HTMLHomeHeaderElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "page-tome": LocalJSX.PageTome & JSXBase.HTMLAttributes<HTMLPageTomeElement>;
        }
    }
}
